# Generated by Django 5.2.8 on 2025-11-26 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='exercise_type',
        ),
    ]
