# Generated by Django 5.2.8 on 2025-11-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_remove_exercise_exercise_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='musclegroup',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='tag',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
