# Generated by Django 5.2.8 on 2025-11-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_musclegroup_icon_tag_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='track_resistance',
            new_name='track_resistance_numeric',
        ),
        migrations.RenameField(
            model_name='exerciseevent',
            old_name='resistance',
            new_name='resistance_numeric',
        ),
        migrations.AddField(
            model_name='exercise',
            name='track_resistance_string',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exerciseevent',
            name='resistance_string',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='track_weight',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='exerciseevent',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance in miles', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='exerciseevent',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='weight in pounds', max_digits=7, null=True),
        ),
    ]
